package com.majerpro.learning_platform.service.quiz;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.majerpro.learning_platform.dto.quiz.GeneratedQuizResponseDto;
import com.majerpro.learning_platform.dto.quiz.QuizQuestionDto;
import com.majerpro.learning_platform.model.Question;
import com.majerpro.learning_platform.model.Skill;
import com.majerpro.learning_platform.model.content.SkillContent;
import com.majerpro.learning_platform.repository.QuestionRepository;
import com.majerpro.learning_platform.repository.SkillRepository;
import com.majerpro.learning_platform.repository.content.SkillContentRepository;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

@Service
public class QuizGenerationServiceImpl implements QuizGenerationService {

    private final SkillRepository skillRepository;
    private final SkillContentRepository skillContentRepository;
    private final QuestionRepository questionRepository;
    private final ObjectMapper objectMapper;

    @Value("${groq.api.url}")
    private String groqApiUrl;

    @Value("${groq.api.key}")
    private String groqApiKey;

    @Value("${groq.api.model}")
    private String groqModel;

    public QuizGenerationServiceImpl(SkillRepository skillRepository,
                                     SkillContentRepository skillContentRepository,
                                     QuestionRepository questionRepository,
                                     ObjectMapper objectMapper) {
        this.skillRepository = skillRepository;
        this.skillContentRepository = skillContentRepository;
        this.questionRepository = questionRepository;
        this.objectMapper = objectMapper;
    }

    @Override
    public void generateAndSaveQuizForSkill(Long skillId, int questionCount) {
        Skill skill = skillRepository.findById(skillId)
                .orElseThrow(() -> new RuntimeException("Skill not found"));

        SkillContent content = skillContentRepository.findBySkillId(skillId).orElse(null);

        String notes = content != null && content.getContent() != null
                ? content.getContent()
                : "No stored notes available.";

        String prompt = buildPrompt(skill.getName(), skill.getDescription(), notes, questionCount);
        String rawJson = callGroq(prompt);
        GeneratedQuizResponseDto response = parseQuizResponse(rawJson);

        if (response.getQuestions() == null || response.getQuestions().isEmpty()) {
            throw new RuntimeException("No questions generated by LLM");
        }

        for (QuizQuestionDto dto : response.getQuestions()) {
            Question question = new Question();
            question.setSkill(skill);
            question.setPrompt(dto.getQuestionText());
            question.setOptionA(dto.getOptionA());
            question.setOptionB(dto.getOptionB());
            question.setOptionC(dto.getOptionC());
            question.setOptionD(dto.getOptionD());

            // IMPORTANT:
            // Replace this setter with your actual Question entity field
            // For example: setAnswer(), setCorrect(), setCorrectAnswer(), etc.
            question.setCorrectOptionIndex(dto.getCorrectOptionIndex());

            question.setExplanation(dto.getExplanation());

            questionRepository.save(question);
        }
    }

    private String buildPrompt(String skillName, String skillDescription, String notes, int questionCount) {
        return """
                You are generating a multiple-choice quiz for a learning platform.

                Generate %d quiz questions for the following skill.

                Skill name: %s
                Skill description: %s
                Skill notes:
                %s

                Rules:
                - Return ONLY valid JSON.
                - No markdown.
                - No explanation outside JSON.
                - Each question must have:
                  - questionText
                  - optionA
                  - optionB
                  - optionC
                  - optionD
                  - correctAnswer
                  - explanation
                - correctAnswer must be one of: A, B, C, D
                - Questions should test understanding, not trivia.

                Expected JSON format:
                {
                  "questions": [
                    {
                      "questionText": "string",
                      "optionA": "string",
                      "optionB": "string",
                      "optionC": "string",
                      "optionD": "string",
                      "correctAnswer": "A",
                      "explanation": "string"
                    }
                  ]
                }
                """.formatted(questionCount, skillName, skillDescription, notes);
    }

    private String callGroq(String prompt) {
        RestTemplate restTemplate = new RestTemplate();

        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        headers.setBearerAuth(groqApiKey);

        String requestBody = """
                {
                  "model": %s,
                  "messages": [
                    {
                      "role": "system",
                      "content": "You generate only valid JSON output."
                    },
                    {
                      "role": "user",
                      "content": %s
                    }
                  ],
                  "temperature": 0.4
                }
                """.formatted(toJsonString(groqModel), toJsonString(prompt));

        HttpEntity<String> entity = new HttpEntity<>(requestBody, headers);

        ResponseEntity<String> response = restTemplate.exchange(
                groqApiUrl,
                HttpMethod.POST,
                entity,
                String.class
        );

        try {
            JsonNode root = objectMapper.readTree(response.getBody());
            JsonNode choices = root.path("choices");

            if (!choices.isArray() || choices.isEmpty()) {
                throw new RuntimeException("Groq response did not contain choices");
            }

            return choices.get(0).path("message").path("content").asText();
        } catch (Exception e) {
            throw new RuntimeException("Failed to extract Groq response", e);
        }
    }

    private GeneratedQuizResponseDto parseQuizResponse(String rawJson) {
        try {
            return objectMapper.readValue(rawJson, GeneratedQuizResponseDto.class);
        } catch (Exception e) {
            throw new RuntimeException("Failed to parse generated quiz JSON: " + rawJson, e);
        }
    }

    private String toJsonString(String value) {
        try {
            return objectMapper.writeValueAsString(value);
        } catch (Exception e) {
            throw new RuntimeException("Failed to encode prompt", e);
        }
    }
}