spring.application.name=Learning Platform

# Database Configuration
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
#server.port=${PORT:8080}
# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/catlc_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:1234}

# Server
server.port=${PORT:8080}

# Judge0
judge0.base-url=${JUDGE0_URL:http://localhost:2358}
judge0.api-key=${JUDGE0_KEY:}

# Gemini
gemini.api.key=${GEMINI_KEY:AIzaSyBKEI-U001BCkZw6latA9fkXw1gkajALuQ}
# Google Gemini Configuration
#gemini.api.key=AIzaSyBKEI-U001BCkZw6latA9fkXw1gkajALuQ
gemini.model=gemini-2.5-flash
gemini.temperature=0.7
gemini.max.tokens=500

# Judge0 configuration
#judge0.base-url=https://localhost:2358
#judge0.api-key=${JUDGE0_KEY}
#judge0.host=judge0-ce.p.rapidapi.com
judge0.poll.max-attempts=15
judge0.poll.delay-ms=700
